// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.orioletech.starxpand_sdk_wrapper

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class InterfaceType(val raw: Int) {
  LAN(0),
  BLUETOOTH(1),
  USB(2);

  companion object {
    fun ofRaw(raw: Int): InterfaceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Device (
  val identifier: String? = null,
  val iface: InterfaceType? = null,
  val model: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Device {
      val identifier = pigeonVar_list[0] as String?
      val iface = pigeonVar_list[1] as InterfaceType?
      val model = pigeonVar_list[2] as String?
      return Device(identifier, iface, model)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      iface,
      model,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Device) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Status (
  val online: Boolean? = null,
  val coverOpen: Boolean? = null,
  val paperEmpty: Boolean? = null,
  val raw: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Status {
      val online = pigeonVar_list[0] as Boolean?
      val coverOpen = pigeonVar_list[1] as Boolean?
      val paperEmpty = pigeonVar_list[2] as Boolean?
      val raw = pigeonVar_list[3] as String?
      return Status(online, coverOpen, paperEmpty, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      online,
      coverOpen,
      paperEmpty,
      raw,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Status) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiscoverOptions (
  val interfaces: List<InterfaceType?>? = null,
  val timeoutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiscoverOptions {
      val interfaces = pigeonVar_list[0] as List<InterfaceType?>?
      val timeoutMs = pigeonVar_list[1] as Long?
      return DiscoverOptions(interfaces, timeoutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      interfaces,
      timeoutMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DiscoverOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectRequest (
  val identifier: String? = null,
  val iface: InterfaceType? = null,
  val monitor: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectRequest {
      val identifier = pigeonVar_list[0] as String?
      val iface = pigeonVar_list[1] as InterfaceType?
      val monitor = pigeonVar_list[2] as Boolean?
      return ConnectRequest(identifier, iface, monitor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      iface,
      monitor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConnectRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ImageRequest (
  val imageBytes: List<Long?>? = null,
  val width: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageRequest {
      val imageBytes = pigeonVar_list[0] as List<Long?>?
      val width = pigeonVar_list[1] as Long?
      return ImageRequest(imageBytes, width)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imageBytes,
      width,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ImageRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          InterfaceType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Device.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Status.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiscoverOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InterfaceType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is Device -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is Status -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DiscoverOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ConnectRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ImageRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface StarHostApi {
  fun startDiscovery(opts: DiscoverOptions)
  fun stopDiscovery()
  fun connect(req: ConnectRequest): Boolean
  fun disconnect()
  fun printImage(req: ImageRequest): Boolean
  fun openCashDrawer(): Boolean
  fun getStatus(): Status

  companion object {
    /** The codec used by StarHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `StarHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StarHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optsArg = args[0] as DiscoverOptions
            val wrapped: List<Any?> = try {
              api.startDiscovery(optsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as ConnectRequest
            val wrapped: List<Any?> = try {
              listOf(api.connect(reqArg))
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.printImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as ImageRequest
            val wrapped: List<Any?> = try {
              listOf(api.printImage(reqArg))
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.openCashDrawer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openCashDrawer())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class StarFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by StarFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
  }
  fun onDeviceFound(deviceArg: Device, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onDeviceFound$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDiscoveryDone(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onDiscoveryDone$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStatus(statusArg: Status, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onStatus$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionComplete(successArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onConnectionComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(successArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
