// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum InterfaceType: Int {
  case lan = 0
  case bluetooth = 1
  case usb = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct Device: Hashable {
  var identifier: String? = nil
  var iface: InterfaceType? = nil
  var model: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Device? {
    let identifier: String? = nilOrValue(pigeonVar_list[0])
    let iface: InterfaceType? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])

    return Device(
      identifier: identifier,
      iface: iface,
      model: model
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      iface,
      model,
    ]
  }
  static func == (lhs: Device, rhs: Device) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Status: Hashable {
  var online: Bool? = nil
  var coverOpen: Bool? = nil
  var paperEmpty: Bool? = nil
  var raw: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Status? {
    let online: Bool? = nilOrValue(pigeonVar_list[0])
    let coverOpen: Bool? = nilOrValue(pigeonVar_list[1])
    let paperEmpty: Bool? = nilOrValue(pigeonVar_list[2])
    let raw: String? = nilOrValue(pigeonVar_list[3])

    return Status(
      online: online,
      coverOpen: coverOpen,
      paperEmpty: paperEmpty,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      online,
      coverOpen,
      paperEmpty,
      raw,
    ]
  }
  static func == (lhs: Status, rhs: Status) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiscoverOptions: Hashable {
  var interfaces: [InterfaceType?]? = nil
  var timeoutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiscoverOptions? {
    let interfaces: [InterfaceType?]? = nilOrValue(pigeonVar_list[0])
    let timeoutMs: Int64? = nilOrValue(pigeonVar_list[1])

    return DiscoverOptions(
      interfaces: interfaces,
      timeoutMs: timeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      interfaces,
      timeoutMs,
    ]
  }
  static func == (lhs: DiscoverOptions, rhs: DiscoverOptions) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectRequest: Hashable {
  var identifier: String? = nil
  var iface: InterfaceType? = nil
  var monitor: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectRequest? {
    let identifier: String? = nilOrValue(pigeonVar_list[0])
    let iface: InterfaceType? = nilOrValue(pigeonVar_list[1])
    let monitor: Bool? = nilOrValue(pigeonVar_list[2])

    return ConnectRequest(
      identifier: identifier,
      iface: iface,
      monitor: monitor
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      iface,
      monitor,
    ]
  }
  static func == (lhs: ConnectRequest, rhs: ConnectRequest) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageRequest: Hashable {
  var imageBytes: [Int64?]? = nil
  var width: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageRequest? {
    let imageBytes: [Int64?]? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])

    return ImageRequest(
      imageBytes: imageBytes,
      width: width
    )
  }
  func toList() -> [Any?] {
    return [
      imageBytes,
      width,
    ]
  }
  static func == (lhs: ImageRequest, rhs: ImageRequest) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InterfaceType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return Device.fromList(self.readValue() as! [Any?])
    case 131:
      return Status.fromList(self.readValue() as! [Any?])
    case 132:
      return DiscoverOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return ConnectRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return ImageRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InterfaceType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? Device {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Status {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DiscoverOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ImageRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol StarHostApi {
  func startDiscovery(opts: DiscoverOptions) throws
  func stopDiscovery() throws
  func connect(req: ConnectRequest) throws -> Bool
  func disconnect() throws
  func printImage(req: ImageRequest) throws -> Bool
  func openCashDrawer() throws -> Bool
  func getStatus() throws -> Status
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class StarHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `StarHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: StarHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optsArg = args[0] as! DiscoverOptions
        do {
          try api.startDiscovery(opts: optsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! ConnectRequest
        do {
          let result = try api.connect(req: reqArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let printImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.printImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! ImageRequest
        do {
          let result = try api.printImage(req: reqArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      printImageChannel.setMessageHandler(nil)
    }
    let openCashDrawerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.openCashDrawer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openCashDrawerChannel.setMessageHandler { _, reply in
        do {
          let result = try api.openCashDrawer()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openCashDrawerChannel.setMessageHandler(nil)
    }
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.starxpand_sdk_wrapper.StarHostApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol StarFlutterApiProtocol {
  func onDeviceFound(device deviceArg: Device, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDiscoveryDone(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStatus(status statusArg: Status, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onLog(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionComplete(success successArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class StarFlutterApi: StarFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  func onDeviceFound(device deviceArg: Device, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onDeviceFound\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDiscoveryDone(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onDiscoveryDone\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStatus(status statusArg: Status, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onStatus\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onLog(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onLog\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionComplete(success successArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.starxpand_sdk_wrapper.StarFlutterApi.onConnectionComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([successArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
